### PR TITLE
ci: Remove protect branch for main

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @suyanhanx and @PsiACE for a review.

**Comment by suyanhanx** [comment]
I'm curious why?

**Comment by Xuanwo** [comment]
> I'm curious why?

We need to push main branch by actions to upload generated artifacts. This repo will only have CI commits in the future.

**Review by suyanhanx — APPROVED** [review]
Thanks!

**Pull request merged**
